In [1]:
import pandas as pd
import numpy as np
import pickle

from sklearn.model_selection import train_test_split

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
train_df = pd.read_csv("../data/processed/cleaned_train.csv")

train_df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,comment_length,clean_comment
0,0000997932d777bf,Explanation\nWhy the edits made under my usern...,0,0,0,0,0,0,264,explanation why the edits made under my userna...
1,000103f0d9cfb60f,D'aww! He matches this background colour I'm s...,0,0,0,0,0,0,112,daww he matches this background colour im seem...
2,000113f07ec002fd,"Hey man, I'm really not trying to edit war. It...",0,0,0,0,0,0,233,hey man im really not trying to edit war its j...
3,0001b41b1c6bb37e,"""\nMore\nI can't make any real suggestions on ...",0,0,0,0,0,0,622,more i cant make any real suggestions on impro...
4,0001d958c54c6e35,"You, sir, are my hero. Any chance you remember...",0,0,0,0,0,0,67,you sir are my hero any chance you remember wh...

In [3]:
target_columns = [
    "toxic",
    "severe_toxic",
    "obscene",
    "threat",
    "insult",
    "identity_hate"
]

In [4]:
X = train_df["clean_comment"]

y = train_df[target_columns]

In [5]:
print(X.shape)
print(y.shape)

(159571,)
(159571, 6)

In [6]:
train_df["clean_comment"] = (
    train_df["clean_comment"]
    .fillna("")
    .astype(str)
)

In [7]:
train_df["clean_comment"].isna().sum()

np.int64(0)

In [8]:
train_df["clean_comment"].dtype

In [9]:
X = train_df["clean_comment"]

print(type(X.iloc[0]))

<class 'str'>

In [10]:
MAX_WORDS = 10000

tokenizer = Tokenizer(
    num_words=MAX_WORDS,
    oov_token="<OOV>"
)

In [11]:
tokenizer.fit_on_texts(X)

In [13]:
train_df[train_df["clean_comment"].isna()]

Empty DataFrame
Columns: [id, comment_text, toxic, severe_toxic, obscene, threat, insult, identity_hate, comment_length, clean_comment]
Index: []

In [14]:
with open("../artifacts/tokenizer.pkl", "wb") as file:
    pickle.dump(tokenizer, file)

In [15]:
len(tokenizer.word_index)

225668

In [16]:
sequences = tokenizer.texts_to_sequences(X)

In [17]:
print(sequences[0])

[640, 76, 2, 122, 127, 172, 29, 631, 4525, 1, 1040, 83, 314, 53, 2037, 1, 51, 6451, 16, 62, 2607, 144, 8, 2765, 34, 115, 1133, 1, 2797, 5, 46, 55, 236, 2, 412, 31, 2, 43, 28, 142, 70, 3352, 90]

In [18]:
MAX_LEN = 200

In [19]:
X_padded = pad_sequences(
    sequences,
    maxlen=MAX_LEN,
    padding="post",
    truncating="post"
)

In [20]:
X_padded.shape

(159571, 200)

In [21]:
X_train, X_val, y_train, y_val = train_test_split(
    X_padded,
    y,
    test_size=0.2,
    random_state=42
)

In [22]:
print(X_train.shape)
print(X_val.shape)

(127656, 200)
(31915, 200)

In [23]:
np.save("../artifacts/X_train.npy", X_train)
np.save("../artifacts/X_val.npy", X_val)

np.save("../artifacts/y_train.npy", y_train)
np.save("../artifacts/y_val.npy", y_val)

In [24]:
X_padded.shape

(159571, 200)

In [25]:
len(tokenizer.word_index)

225668